# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3cd0427e-119c-44b5-b328-250bef203762";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/bbe97718-49a7-49e5-91ba-e7573c9c2606";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
